### ISSUE TITLE
Remove unnecessary views

### ISSUE THREAD

**Issue by WtheFourth** [newtonrd/InventoryManagement-BT#1]
Basically all of https://github.com/newtonrd/InventoryManagement-BT/tree/master/InventoryManagement-BT/Views/Account can be removed, as well as several of the Shared and Home views.

**Comment by WtheFourth** [comment]
https://github.com/newtonrd/InventoryManagement-BT/tree/master/InventoryManagement-BT/Views/Manage can also probably be removed.

**Comment by WtheFourth** [comment]
https://github.com/newtonrd/InventoryManagement-BT/tree/master/InventoryManagement-BT/Views/Shared 

Error, Lockout, and _LoginPartial can be removed.

**Comment by newtonrd** [comment]
Closing as resolved
