### ISSUE TITLE
.DefaultIfEmpty() could lead to data discrepancies

### ISSUE THREAD

**Issue by WtheFourth** [newtonrd/InventoryManagement-BT#10]
https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Services/InventoryManagementRepository.cs#L34

Basically, if no `Assets` are returned, it's going to return a default, probably empty `Asset`. If you're doing this so you can do like a Search or Create then it's fine though.

**Comment by newtonrd** [comment]
DefaultIfEmpty() is used for a search. I'll close this as a non issue
