### ISSUE TITLE
Validation Attributes Should Be in Your Models

### ISSUE THREAD

**Issue by mjknowles** [newtonrd/InventoryManagement-BT#13]
Typically, at least I'm pretty sure typically, you're gonna want your validation attributes on your Model classes and not your ViewModel classes. Your ViewModels are gonna be pretty lightweight "property bag" type objects focused specifically on what data you want to send to your view and what its gonna look like. Validation logic is more of a "domain" concern that needs to be present at the very bottom layer and not just your presentation logic.

**Comment by newtonrd** [comment]
This has a `kinda` dependency on #3.
