### ISSUE TITLE
Remove unnecessary controller actions

### ISSUE THREAD

**Issue by WtheFourth** [newtonrd/InventoryManagement-BT#2]
Lines 16-28 of https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Controllers/HomeController.cs#L16-L28, https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Controllers/AccountController.cs, and probably https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Controllers/ManageController.cs can be removed.

**Comment by newtonrd** [comment]
Closing this as resolved
