### ISSUE TITLE
Move all directive blocks to top of file

### ISSUE THREAD

**Issue by WtheFourth** [newtonrd/InventoryManagement-BT#4]
https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Models/Model.cs#L3-L5 

https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Models/Asset.cs#L3-L8

https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Models/Product.cs#L3-L6

The directives highlighted should be outside of the namespace declaration.

**Comment by newtonrd** [comment]
Closing as resolved
